### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by benhaynes** [directus/extension-static-generator#21]
Right now, it generates an index.html in the root even though there's no route for that. I added a file with this route:

`<!--- directus_route: / --->` 

But it doesn't seem to generate

**Comment by benhaynes** [comment]
Also, is there a reason the route comment has `---` instead of the typical `--`?

https://www.w3schools.com/html/html_comments.asp

**Comment by jasekz** [comment]
'/' is the 'home' route, so it should generate so that it's accessible when going to 'mysite.com/' or 'mysite.com'.  It should work for something like this: '<a href="/">Home</a>'.

As for the triple dashes vs. two, that's so that 'directus directives' do not get mixed in with comments.  Basically, anything with the three dashes will be treated as a directus directive, if there are any in the future.

**Comment by benhaynes** [comment]
1. Why is this file generated by default? There is no homepage route in the example code... so this should not be here:

![screen shot 2017-10-09 at 6 42 51 pm](https://user-images.githubusercontent.com/522079/31361519-b74ebfc8-ad21-11e7-82a2-62b017bd67ac.png)
